<?php

return [

    /* ================= RESEP PILIHAN ================= */

    'ayam-rica-rica' => [
        'title' => 'Ayam Rica-Rica',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125515-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '45 Menit',
        'level' => 'Sedang',
        'serve' => '6 Orang',
        'ingredients' => [
            '1 ekor ayam kampung ±1 kg, potong 10–12 bagian',
            '2 batang serai, memarkan',
            '4 lembar daun jeruk, buang tulang daun',
            '2 lembar daun salam',
            '6 siung bawang merah',
            '4 siung bawang putih',
            '8 buah cabai merah besar',
            '10 buah cabai rawit merah (sesuai selera)',
            '1 ruas jahe ±3 cm',
            '1 ruas lengkuas ±3 cm',
            '1 sdt garam',
            '½ sdt gula pasir',
            '½ sdt kaldu bubuk (opsional)',
            '200 ml air',
            '3 sdm minyak goreng',
        ],
        'steps' => [
            'Cuci bersih ayam di bawah air mengalir lalu tiriskan hingga airnya benar-benar turun.',
            'Haluskan bawang merah, bawang putih, cabai merah, cabai rawit, jahe, dan lengkuas menggunakan blender atau ulekan.',
            'Panaskan minyak dalam wajan, tumis bawang merah iris hingga harum dan sedikit layu.',
            'Masukkan bumbu halus, tumis dengan api sedang hingga matang dan minyak mulai terpisah.',
            'Masukkan serai, daun jeruk, dan daun salam, aduk hingga aromanya keluar.',
            'Masukkan potongan ayam, aduk hingga ayam berubah warna dan terbalut bumbu.',
            'Tuangkan air, masak dengan api sedang hingga ayam empuk.',
            'Tambahkan garam, gula, dan kaldu bubuk, aduk rata dan koreksi rasa.',
            'Masak terus hingga kuah menyusut dan bumbu meresap sempurna.',
            'Angkat dan sajikan ayam rica-rica selagi hangat.',
        ],
    ],

    'opor-ayam' => [
        'title' => 'Opor Ayam',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/230519-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '60 Menit',
        'level' => 'Mudah',
        'serve' => '4 Orang',
        'ingredients' => [
            '1 ekor ayam, potong 8 bagian',
            '600 ml santan cair',
            '200 ml santan kental',
            '2 batang serai, memarkan',
            '3 lembar daun salam',
            '6 siung bawang merah',
            '4 siung bawang putih',
            '3 butir kemiri',
            '1 ruas kunyit',
            '1 ruas jahe',
            '1 sdt garam',
            '½ sdt gula pasir',
            '2 sdm minyak goreng',
        ],
        'steps' => [
            'Haluskan bawang merah, bawang putih, kemiri, kunyit, dan jahe hingga benar-benar halus.',
            'Panaskan minyak, tumis bumbu halus hingga harum dan matang.',
            'Masukkan serai dan daun salam, aduk hingga aromanya keluar.',
            'Masukkan potongan ayam, aduk hingga ayam berubah warna.',
            'Tuangkan santan cair, masak dengan api kecil sambil sesekali diaduk agar santan tidak pecah.',
            'Masukkan santan kental, garam, dan gula.',
            'Masak hingga ayam empuk dan kuah mengental.',
            'Angkat dan sajikan opor ayam hangat.',
        ],
    ],

    'tumis-kangkung' => [
        'title' => 'Tumis Kangkung',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/230520-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '15 Menit',
        'level' => 'Mudah',
        'serve' => '2 Orang',
        'ingredients' => [
            '1 ikat kangkung, petik dan cuci bersih',
            '4 siung bawang putih, iris tipis',
            '6 buah cabai rawit merah',
            '1 sdt saus tiram',
            '½ sdt garam',
            '¼ sdt gula pasir',
            '2 sdm minyak goreng',
        ],
        'steps' => [
            'Panaskan minyak dalam wajan dengan api sedang.',
            'Tumis bawang putih dan cabai rawit hingga harum.',
            'Masukkan kangkung, aduk cepat hingga mulai layu.',
            'Tambahkan saus tiram, garam, dan gula.',
            'Masak sebentar hingga kangkung matang.',
            'Angkat dan sajikan segera agar tetap segar.',
        ],
    ],

    /* ================= RESEP LAINNYA ================= */

    'nasi-kebuli' => [
        'title' => 'Nasi Kebuli',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/230922-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '90 Menit',
        'level' => 'Sulit',
        'serve' => '6 Orang',
        'ingredients' => [
            '500 gr beras basmati',
            '500 gr daging kambing atau ayam',
            '750 ml air atau kaldu',
            '200 ml susu cair',
            '5 siung bawang putih',
            '8 siung bawang merah',
            '2 batang serai',
            '5 butir kapulaga',
            '3 butir cengkeh',
            '1 batang kayu manis',
            '1 sdt garam',
            '1 sdt gula',
            '3 sdm minyak samin',
        ],
        'steps' => [
            'Cuci beras basmati hingga bersih lalu rendam selama 30 menit.',
            'Tumis bawang merah dan bawang putih hingga harum.',
            'Masukkan daging, masak hingga berubah warna.',
            'Tambahkan rempah-rempah dan minyak samin.',
            'Masukkan beras, air, dan susu.',
            'Masak hingga nasi matang dan pulen.',
        ],
    ],

    'soto-ayam' => [
        'title' => 'Soto Ayam',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125763-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '60 Menit',
        'level' => 'Mudah',
        'serve' => '4 Orang',
        'ingredients' => [
            '1 ekor ayam',
            '2 liter air',
            '2 batang serai',
            '3 lembar daun jeruk',
            '4 siung bawang putih',
            '6 siung bawang merah',
            '1 ruas kunyit',
            '1 ruas jahe',
            '1 sdt garam',
        ],
        'steps' => [
            'Rebus ayam hingga matang lalu suwir dagingnya.',
            'Tumis bumbu halus hingga harum.',
            'Masukkan ke dalam air rebusan.',
            'Masukkan ayam suwir dan masak hingga mendidih.',
            'Sajikan dengan pelengkap.',
        ],
    ],

    'sayur-lodeh' => [
        'title' => 'Sayur Lodeh',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/230915-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '40 Menit',
        'level' => 'Mudah',
        'serve' => '4 Orang',
        'ingredients' => [
            '300 ml santan',
            '1 buah terong',
            '100 gr kacang panjang',
            '2 lembar daun salam',
            '3 siung bawang putih',
            '5 siung bawang merah',
            '1 sdt garam',
        ],
        'steps' => [
            'Rebus santan dan daun salam.',
            'Masukkan bumbu halus.',
            'Tambahkan sayuran.',
            'Masak hingga matang.',
        ],
    ],

    'sop-buntut' => [
        'title' => 'Sop Buntut',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125214-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '120 Menit',
        'level' => 'Sedang',
        'serve' => '4 Orang',
        'ingredients' => [
            '1 kg buntut sapi',
            '2 liter air',
            '2 buah wortel',
            '2 kentang',
            '4 siung bawang putih',
            '1 sdt garam',
        ],
        'steps' => [
            'Rebus buntut hingga empuk.',
            'Masukkan bumbu dan sayuran.',
            'Masak hingga kuah gurih.',
        ],
    ],

    'tumis-sapi-saus-bawang' => [
        'title' => 'Tumis Sapi Saos Bawang',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125570-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '30 Menit',
        'level' => 'Mudah',
        'serve' => '3 Orang',
        'ingredients' => [
            '300 gr daging sapi',
            '1 bawang bombay',
            '3 siung bawang putih',
            '2 sdm saus tiram',
            '1 sdt kecap manis',
        ],
        'steps' => [
            'Tumis bawang hingga harum.',
            'Masukkan daging dan saus.',
            'Masak hingga matang.',
        ],
    ],

    'rawon-daging-sapi' => [
        'title' => 'Rawon Daging Sapi',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125611-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '90 Menit',
        'level' => 'Sedang',
        'serve' => '4 Orang',
        'ingredients' => [
            '500 gr daging sapi',
            '3 buah kluwek',
            '4 siung bawang putih',
            '6 siung bawang merah',
            '1 sdt garam',
        ],
        'steps' => [
            'Rebus daging hingga empuk.',
            'Tumis bumbu halus.',
            'Masukkan ke rebusan.',
            'Masak hingga hitam pekat.',
        ],
    ],

    'sup-tomat-daging-asap' => [
        'title' => 'Sup Tomat Daging Asap',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125641-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '35 Menit',
        'level' => 'Mudah',
        'serve' => '3 Orang',
        'ingredients' => [
            '200 gr daging asap',
            '3 buah tomat merah',
            '1 bawang bombay',
            '500 ml air',
            '1 sdt garam',
        ],
        'steps' => [
            'Tumis bawang hingga harum.',
            'Masukkan tomat dan daging asap.',
            'Tuangkan air dan masak hingga matang.',
        ],
    ],

        'iga-konro-bakar' => [
        'title' => 'Iga Konro Bakar',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125014-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '120 Menit',
        'level' => 'Sedang',
        'serve' => '4 Orang',
        'ingredients' => [
            '1 kg iga sapi',
            '2 liter air',
            '6 siung bawang merah',
            '4 siung bawang putih',
            '3 butir kemiri',
            '1 sdt ketumbar',
            '1 ruas jahe',
            '1 ruas lengkuas',
            '2 lembar daun salam',
            '1 sdt garam',
            '1 sdt gula',
            '3 sdm kecap manis',
        ],
        'steps' => [
            'Rebus iga sapi dengan air hingga empuk dan kaldu keluar.',
            'Haluskan bawang merah, bawang putih, kemiri, ketumbar, jahe, dan lengkuas.',
            'Tumis bumbu halus hingga harum dan matang.',
            'Masukkan bumbu tumis ke dalam rebusan iga.',
            'Tambahkan daun salam, garam, dan gula, masak hingga bumbu meresap.',
            'Angkat iga, lumuri dengan kecap manis.',
            'Bakar iga di atas panggangan hingga kecokelatan.',
            'Sajikan iga konro bakar selagi hangat.',
        ],
    ],

    'bakwan-oncom-renyah' => [
        'title' => 'Bakwan Oncom Renyah',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125004-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '30 Menit',
        'level' => 'Mudah',
        'serve' => '4 Orang',
        'ingredients' => [
            '200 gr oncom, hancurkan',
            '100 gr tepung terigu',
            '2 batang daun bawang, iris',
            '2 siung bawang putih, haluskan',
            '½ sdt garam',
            '¼ sdt lada',
            'Air secukupnya',
            'Minyak untuk menggoreng',
        ],
        'steps' => [
            'Campurkan oncom, tepung terigu, daun bawang, dan bawang putih.',
            'Tambahkan garam, lada, dan air secukupnya hingga adonan kental.',
            'Panaskan minyak dengan api sedang.',
            'Ambil adonan, goreng hingga keemasan.',
            'Angkat dan tiriskan.',
            'Sajikan bakwan oncom selagi hangat.',
        ],
    ],

    'tahu-tempe-endes' => [
        'title' => 'Tahu Tempe Endes',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125717-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '25 Menit',
        'level' => 'Mudah',
        'serve' => '3 Orang',
        'ingredients' => [
            '200 gr tahu, potong dadu',
            '200 gr tempe, potong dadu',
            '3 siung bawang putih',
            '5 buah cabai merah',
            '1 sdt gula',
            '1 sdt garam',
            '2 sdm minyak',
        ],
        'steps' => [
            'Goreng tahu dan tempe hingga setengah kering, tiriskan.',
            'Haluskan bawang putih dan cabai merah.',
            'Tumis bumbu halus hingga harum.',
            'Masukkan tahu dan tempe goreng.',
            'Tambahkan garam dan gula.',
            'Aduk hingga bumbu meresap.',
            'Angkat dan sajikan.',
        ],
    ],

    'tempe-asem-pedas' => [
        'title' => 'Tempe Asem Pedas',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125730-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '30 Menit',
        'level' => 'Mudah',
        'serve' => '3 Orang',
        'ingredients' => [
            '300 gr tempe, potong',
            '4 siung bawang merah',
            '3 siung bawang putih',
            '5 buah cabai merah',
            '2 sdm air asam jawa',
            '1 sdt gula',
            '1 sdt garam',
            '2 sdm minyak',
        ],
        'steps' => [
            'Goreng tempe hingga kecokelatan, tiriskan.',
            'Haluskan bawang merah, bawang putih, dan cabai.',
            'Tumis bumbu halus hingga harum.',
            'Masukkan air asam jawa, gula, dan garam.',
            'Masukkan tempe goreng, aduk rata.',
            'Masak hingga bumbu meresap.',
            'Angkat dan sajikan.',
        ],
    ],

    'tempe-mendoan' => [
        'title' => 'Tempe Mendoan',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/207335-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '20 Menit',
        'level' => 'Mudah',
        'serve' => '4 Orang',
        'ingredients' => [
            '300 gr tempe mendoan',
            '100 gr tepung terigu',
            '2 batang daun bawang',
            '1 siung bawang putih',
            '½ sdt garam',
            'Air secukupnya',
            'Minyak untuk menggoreng',
        ],
        'steps' => [
            'Campurkan tepung, bawang putih, daun bawang, dan garam.',
            'Tambahkan air hingga adonan encer.',
            'Celupkan tempe ke adonan.',
            'Goreng sebentar hingga setengah matang.',
            'Angkat dan sajikan hangat.',
        ],
    ],

    'tempe-bakar-sambal-kemangi' => [
        'title' => 'Tempe Bakar Sambal Kemangi',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/208273-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '35 Menit',
        'level' => 'Mudah',
        'serve' => '3 Orang',
        'ingredients' => [
            '300 gr tempe',
            '5 buah cabai merah',
            '3 siung bawang merah',
            '1 sdt terasi',
            '1 genggam daun kemangi',
            '1 sdt garam',
        ],
        'steps' => [
            'Bakar tempe hingga kecokelatan.',
            'Haluskan cabai, bawang, dan terasi.',
            'Campur sambal dengan daun kemangi.',
            'Lumuri tempe bakar dengan sambal.',
            'Sajikan hangat.',
        ],
    ],

    'tumis-tempe' => [
        'title' => 'Tumis Tempe',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/230521-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '20 Menit',
        'level' => 'Mudah',
        'serve' => '2 Orang',
        'ingredients' => [
            '250 gr tempe',
            '3 siung bawang putih',
            '2 sdm kecap manis',
            '1 sdt garam',
            '2 sdm minyak',
        ],
        'steps' => [
            'Goreng tempe setengah matang.',
            'Tumis bawang putih hingga harum.',
            'Masukkan tempe dan kecap.',
            'Tambahkan garam, aduk rata.',
            'Masak hingga bumbu meresap.',
        ],
    ],

    'tumis-pakcoy-saus-kepiting' => [
        'title' => 'Tumis Pakcoy Saus Kepiting',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125531-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '25 Menit',
        'level' => 'Mudah',
        'serve' => '3 Orang',
        'ingredients' => [
            '300 gr pakcoy',
            '3 siung bawang putih',
            '2 sdm saus kepiting',
            '½ sdt garam',
            '2 sdm minyak',
        ],
        'steps' => [
            'Panaskan minyak, tumis bawang putih.',
            'Masukkan pakcoy, aduk cepat.',
            'Tambahkan saus kepiting dan garam.',
            'Masak hingga pakcoy layu.',
            'Angkat dan sajikan.',
        ],
    ],

    'brokoli-saus-jamur' => [
        'title' => 'Brokoli Saus Jamur',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125581-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '25 Menit',
        'level' => 'Mudah',
        'serve' => '3 Orang',
        'ingredients' => [
            '300 gr brokoli',
            '100 gr jamur',
            '3 siung bawang putih',
            '2 sdm saus tiram',
            '½ sdt garam',
        ],
        'steps' => [
            'Rebus brokoli hingga setengah matang.',
            'Tumis bawang putih hingga harum.',
            'Masukkan jamur dan saus tiram.',
            'Masukkan brokoli, aduk rata.',
            'Masak sebentar lalu sajikan.',
        ],
    ],

    'tumis-kailan-bawang-putih' => [
        'title' => 'Tumis Kailan Bawang Putih',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125647-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '20 Menit',
        'level' => 'Mudah',
        'serve' => '2 Orang',
        'ingredients' => [
            '300 gr kailan',
            '4 siung bawang putih',
            '½ sdt garam',
            '2 sdm minyak',
        ],
        'steps' => [
            'Panaskan minyak, tumis bawang putih hingga harum.',
            'Masukkan kailan, aduk cepat.',
            'Tambahkan garam.',
            'Masak hingga layu.',
            'Angkat dan sajikan.',
        ],
    ],

        'sup-krim-ayam-istimewa' => [
        'title' => 'Sup Krim Ayam Istimewa',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125690-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '30 Menit',
        'level' => 'Mudah',
        'serve' => '3 Orang',
        'ingredients' => [
            '250 gr dada ayam fillet, potong dadu kecil',
            '1 buah wortel, potong dadu',
            '½ bawang bombay, cincang halus',
            '2 siung bawang putih, cincang',
            '500 ml susu cair',
            '250 ml kaldu ayam',
            '2 sdm mentega',
            '2 sdm tepung terigu',
            '½ sdt lada bubuk',
            '1 sdt garam',
        ],
        'steps' => [
            'Lelehkan mentega dalam panci dengan api kecil.',
            'Tumis bawang bombay dan bawang putih hingga harum dan layu.',
            'Masukkan ayam, masak hingga berubah warna.',
            'Masukkan tepung terigu, aduk cepat hingga tercampur rata.',
            'Tuangkan susu dan kaldu sedikit demi sedikit sambil diaduk agar tidak menggumpal.',
            'Masukkan wortel, garam, dan lada.',
            'Masak hingga sup mengental dan ayam matang.',
            'Angkat dan sajikan selagi hangat.',
        ],
    ],

    'tumis-tahu-hijau' => [
        'title' => 'Tumis Tahu Hijau',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125720-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '25 Menit',
        'level' => 'Mudah',
        'serve' => '3 Orang',
        'ingredients' => [
            '300 gr tahu hijau, potong kotak',
            '3 siung bawang putih, iris',
            '5 buah cabai hijau, iris serong',
            '1 sdm saus tiram',
            '½ sdt garam',
            '2 sdm minyak goreng',
        ],
        'steps' => [
            'Goreng tahu hingga setengah kering, tiriskan.',
            'Panaskan minyak, tumis bawang putih hingga harum.',
            'Masukkan cabai hijau, aduk rata.',
            'Masukkan tahu goreng dan saus tiram.',
            'Tambahkan garam, aduk hingga bumbu meresap.',
            'Angkat dan sajikan.',
        ],
    ],

    'cumi-krispi-cocol-madu' => [
        'title' => 'Cumi Krispi Cocol Madu',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125699-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '25 Menit',
        'level' => 'Sedang',
        'serve' => '3 Orang',
        'ingredients' => [
            '300 gr cumi segar, potong cincin',
            '100 gr tepung terigu',
            '50 gr tepung maizena',
            '½ sdt garam',
            '½ sdt lada',
            'Minyak untuk menggoreng',
            '3 sdm madu',
            '1 sdm saus sambal',
            '1 sdt air jeruk nipis',
        ],
        'steps' => [
            'Cuci bersih cumi dan tiriskan hingga kering.',
            'Campurkan tepung terigu, maizena, garam, dan lada.',
            'Gulingkan cumi ke dalam campuran tepung hingga rata.',
            'Goreng dalam minyak panas hingga keemasan dan renyah.',
            'Angkat dan tiriskan.',
            'Campur madu, saus sambal, dan air jeruk nipis.',
            'Sajikan cumi krispi dengan saus madu.',
        ],
    ],

    'nasi-goreng-cumi' => [
        'title' => 'Nasi Goreng Cumi',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125733-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '20 Menit',
        'level' => 'Mudah',
        'serve' => '2 Orang',
        'ingredients' => [
            '2 piring nasi putih',
            '150 gr cumi, potong kecil',
            '3 siung bawang putih, cincang',
            '2 butir telur',
            '2 sdm kecap manis',
            '½ sdt garam',
            '½ sdt lada',
            '2 sdm minyak',
        ],
        'steps' => [
            'Panaskan minyak, tumis bawang putih hingga harum.',
            'Masukkan cumi, masak hingga matang.',
            'Masukkan telur, orak-arik hingga setengah matang.',
            'Masukkan nasi, aduk rata.',
            'Tambahkan kecap, garam, dan lada.',
            'Masak hingga nasi panas dan tercampur rata.',
            'Angkat dan sajikan.',
        ],
    ],

    'telur-gembung' => [
        'title' => 'Telur Gembung',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125615-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '15 Menit',
        'level' => 'Mudah',
        'serve' => '2 Orang',
        'ingredients' => [
            '4 butir telur ayam',
            '½ sdt garam',
            'Minyak goreng secukupnya',
        ],
        'steps' => [
            'Panaskan minyak agak banyak dalam wajan.',
            'Pecahkan telur satu per satu ke dalam minyak panas.',
            'Siram-siram bagian atas telur dengan minyak agar mengembang.',
            'Tambahkan garam.',
            'Angkat setelah bagian luar garing.',
            'Sajikan selagi hangat.',
        ],
    ],

    'risoles-ayam-telur-asin' => [
        'title' => 'Risoles Ayam Telur Asin',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125634-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '60 Menit',
        'level' => 'Sedang',
        'serve' => '5 Orang',
        'ingredients' => [
            'Kulit risoles siap pakai',
            '200 gr ayam rebus, suwir',
            '2 butir telur asin, haluskan',
            '2 siung bawang putih',
            '2 sdm tepung terigu',
            '300 ml susu cair',
            'Tepung panir secukupnya',
            'Minyak goreng',
        ],
        'steps' => [
            'Tumis bawang putih hingga harum.',
            'Masukkan ayam suwir dan telur asin.',
            'Masukkan tepung terigu dan susu, aduk hingga kental.',
            'Ambil kulit risoles, isi dengan adonan.',
            'Gulung dan rekatkan.',
            'Gulingkan ke tepung panir.',
            'Goreng hingga keemasan.',
        ],
    ],

    'makaroni-keju' => [
        'title' => 'Makaroni Keju',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125548-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '30 Menit',
        'level' => 'Mudah',
        'serve' => '3 Orang',
        'ingredients' => [
            '200 gr makaroni',
            '100 gr keju parut',
            '2 sdm mentega',
            '200 ml susu cair',
            '½ sdt garam',
            '½ sdt lada',
        ],
        'steps' => [
            'Rebus makaroni hingga matang, tiriskan.',
            'Lelehkan mentega dalam wajan.',
            'Masukkan susu dan keju, aduk hingga meleleh.',
            'Masukkan makaroni.',
            'Tambahkan garam dan lada.',
            'Aduk hingga tercampur rata.',
            'Sajikan hangat.',
        ],
    ],

    'nasi-goreng-spicy' => [
        'title' => 'Nasi Goreng Spicy',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125572-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '20 Menit',
        'level' => 'Mudah',
        'serve' => '2 Orang',
        'ingredients' => [
            '2 piring nasi putih',
            '5 buah cabai rawit',
            '3 siung bawang putih',
            '2 butir telur',
            '2 sdm kecap manis',
            '½ sdt garam',
            '2 sdm minyak',
        ],
        'steps' => [
            'Haluskan cabai dan bawang putih.',
            'Tumis bumbu halus hingga harum.',
            'Masukkan telur, orak-arik.',
            'Masukkan nasi dan kecap.',
            'Tambahkan garam.',
            'Masak hingga nasi tercampur rata.',
            'Sajikan panas.',
        ],
    ],

    'ifumie-saus-jamur' => [
        'title' => 'Ifumie Saos Jamur',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125588-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '35 Menit',
        'level' => 'Sedang',
        'serve' => '3 Orang',
        'ingredients' => [
            '1 porsi mie telur',
            '150 gr jamur',
            '3 siung bawang putih',
            '2 sdm saus tiram',
            '1 sdt maizena larut air',
            '300 ml air',
        ],
        'steps' => [
            'Goreng mie hingga kering dan renyah.',
            'Tumis bawang putih hingga harum.',
            'Masukkan jamur dan saus tiram.',
            'Tambahkan air dan larutan maizena.',
            'Masak hingga saus mengental.',
            'Siram saus di atas mie.',
            'Sajikan segera.',
        ],
    ],

    'ikan-goreng-telur-asin' => [
        'title' => 'Ikan Goreng Telur Asin',
        'img'   => 'https://assets.unileversolutions.com/recipes-v3/125541-default.jpg?im=AspectCrop=(720,459);Resize=(720,459)',
        'time'  => '35 Menit',
        'level' => 'Sedang',
        'serve' => '3 Orang',
        'ingredients' => [
            '500 gr ikan fillet',
            '2 butir telur asin',
            '3 siung bawang putih',
            '1 sdt gula',
            '½ sdt garam',
            'Minyak goreng',
        ],
        'steps' => [
            'Goreng ikan hingga matang dan garing.',
            'Haluskan telur asin dan bawang putih.',
            'Tumis campuran telur asin hingga harum.',
            'Masukkan ikan goreng.',
            'Tambahkan gula dan garam.',
            'Aduk hingga ikan terbalut saus.',
            'Sajikan hangat.',
        ],
    ],

];
